#!/usr/bin/env python3
"""Write the block reference (types, parameters, ports) from the registry's ParamSpecs.

    python3 scripts/write_block_reference.py [OUT.md]     (default: ../../docs/blocks/blocks.md)
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(os.path.dirname(HERE), "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from tiago_ring_controller.blocks import REGISTRY  # noqa: E402

DEFAULT_OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(HERE))), "docs", "blocks", "blocks.md")


def fmt(value):
    if isinstance(value, float):
        return ("%g" % value) if abs(value) < 1e6 else ("%.3g" % value)
    if isinstance(value, (dict, list)):
        return "`%s`" % (value if value else ("{}" if isinstance(value, dict) else "[]"))
    return str(value)


def render():
    lines = [
        "# Block reference",
        "",
        "Generated by `scripts/write_block_reference.py` from `tiago_ring_controller.blocks.REGISTRY`;",
        "do not edit by hand. Ports: **spikes** ports carry NEST node collections and are",
        "wired at build time; **signal** ports carry a value once per tick. A *late* input is",
        "connected after both blocks exist (the target owns the pattern), which is how",
        "feedback cycles build. *multi* inputs accept several producers.",
        "",
    ]
    for name, cls in REGISTRY.items():
        description = cls.describe_type()
        lines.append("## %s%s" % (name, " (composite)" if getattr(cls, "composite", False) else ""))
        lines.append("")
        doc = (cls.__doc__ or "").strip()
        if doc:
            lines.append(doc)
            lines.append("")
        lines.append("Neural: %s. Version %d." % ("yes" if description["neural"] else "no", description["version"]))
        lines.append("")
        lines.append("| parameter | type | default | bounds / choices | unit | doc |")
        lines.append("|---|---|---|---|---|---|")
        for spec in description["params"]:
            bounds = []
            if "minimum" in spec:
                bounds.append("≥ %s" % fmt(spec["minimum"]))
            if "maximum" in spec:
                bounds.append("≤ %s" % fmt(spec["maximum"]))
            if "choices" in spec:
                bounds.append(", ".join(str(c) for c in spec["choices"]))
            lines.append("| `%s` | %s | %s | %s | %s | %s |" % (
                spec["name"], spec["type"], fmt(spec["default"]), "; ".join(bounds), spec.get("unit", ""),
                spec.get("doc", "").replace("|", "\\|")))
        lines.append("")
        lines.append("| port | kind | direction | notes |")
        lines.append("|---|---|---|---|")
        for port in description["ports"]:
            notes = []
            if port["direction"] == "in":
                notes.append("required" if port["required"] else "optional")
                if port["multi"]:
                    notes.append("multi")
                if port["late"]:
                    notes.append("late")
            if port["doc"]:
                notes.append(port["doc"])
            lines.append("| `%s` | %s | %s | %s |" % (port["name"], port["kind"], port["direction"], "; ".join(notes)))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    out = (argv or sys.argv[1:] or [DEFAULT_OUT])[0]
    with open(out, "w", encoding="utf-8") as stream:
        stream.write(render())
    print("written:", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
